function f=aboutRegistration()
%About box for the Optode Positioning Registration tool
%
%
% Copyright 2009-12
% @date: 1-Apr-2009
% @author Felipe Orihuela-Espina
% @date: 30-Dec-2012
%

%% Initialize the figure
%...and hide the GUI as it is being constructed
width=600;
height=320;
scSize= get( 0, 'ScreenSize' );
    %WATCH OUT!  The ScreenSize property is static. Its values
    %are read-only at MATLAB startup and not updated if system
    %display settings change.
    %
    %There seems to be a dynamic version:
    %
    %   http://www.mathworks.com/matlabcentral/fileexchange/10957-get-screen-size-dynamic
    %
    %but I haven't tested.
    %

f=figure('Visible','off',...
         'Position',[round((scSize(3)-width)/2),...
                     round((scSize(4)-height)/2),...
                     width,...
                     height]);

set(f,'NumberTitle','off');
set(f,'MenuBar','none'); %Hide MATLAB figure menu

%% Add components
fontSize=13;
bgColor=get(f,'Color');
uicontrol(f,'Style', 'text',...
       'String', 'Optode Positioning Registration Tool',...
       'BackgroundColor',bgColor,...
       'FontSize',fontSize,...
       'HorizontalAlignment','left',...
       'Position', [round(0.05*width) height-20-(fontSize*1.5) ...
                    round(0.9*width) fontSize*1.5]);

uicontrol(f,'Style', 'text',...
       'String', 'This tool is part of ICAF',...
       'BackgroundColor',bgColor,...
       'FontSize',fontSize,...
       'HorizontalAlignment','left',...
       'Position', [round(0.05*width) height-50-(fontSize*1.5) ...
                    round(0.9*width) fontSize*1.5]);

uicontrol(f,'Style', 'text',...
       'String', 'Author: Felipe Orihuela-Espina',...
       'BackgroundColor',bgColor,...
       'FontSize',fontSize,...
       'HorizontalAlignment','left',...
       'Position', [round(0.05*width) height-80-(fontSize*1.5) ...
                    round(0.9*width) fontSize*1.5]);

uicontrol(f,'Style', 'text',...
       'String', ['(c) 2008-2013 Felipe Orihuela-Espina. ' ...
                'Imperial College London'],...
       'BackgroundColor',bgColor,...
       'FontSize',fontSize,...
       'HorizontalAlignment','left',...
       'Position', [round(0.05*width) height-110-(fontSize*1.5) ...
                    round(0.9*width) fontSize*1.5]);

                

% A=imread('./GUI/icons/Registration.jpg','jpeg');
% image(A);
% set(gca,'Tag','logoAxes',...
%        'Color','w',...
%        'FontSize',fontSize,...
%        'Units','normalize',...
%        'Position', [0.37 0.15 0.26 0.35]);
% axis off

%% Make GUI visible
set(f,'Name','About Registration');
movegui(f,'center'); %Move the window to the center of the screen
set(f,'Visible','on');


end