function f=aboutICNNA()
%Display the "About ICNNA" information window
%
%
% Copyright 2008-18
% @date: 20-Apr-2008
% @author Felipe Orihuela-Espina
%



%% Log
%
% 25-May-2018: FOE. Renamed from aboutICNA to aboutICNNA
%
% 30-Oct-2019: FOE. Added Harsimrat and Michele as beta
%   testers. Now includes version number.
%   About window size now depends on screen size.
%   Software title is rendered in bold.
%




%% Initialize the figure
%...and hide the GUI as it is being constructed
scSize= get( 0, 'ScreenSize' );
    %WATCH OUT!  The ScreenSize property is static. Its values
    %are read-only at MATLAB startup and not updated if system
    %display settings change.
    %
    %There seems to be a dynamic version:
    %
    %   http://www.mathworks.com/matlabcentral/fileexchange/10957-get-screen-size-dynamic
    %
    %but I haven't tested.
    %

width=0.5*scSize(3);
height=0.5*scSize(4);
f=figure('Visible','off',...
         'Position',[round((scSize(3)-width)/2),...
                     round((scSize(4)-height)/2),...
                     width,...
                     height]);
set(f,'NumberTitle','off');
set(f,'MenuBar','none'); %Hide MATLAB figure menu

%% Add components
fontSize=10;
bgColor=get(f,'Color');



% uicontrol(f,'Style', 'text',...
%        'String', 'Imperial College Neuroimage Analysis (ICNA)',...
%        'BackgroundColor',bgColor,...
%        'FontSize',fontSize,...
%        'HorizontalAlignment','left',...
%        'Position', [round(0.3*width) height-20-(fontSize*1.5) ...
%                     round(0.65*width) fontSize*2]);

uicontrol(f,'Style', 'text',...
       'String', 'Imperial College Near Infrared Spectroscopy Neuroimaging Analysis (ICNNA)',...
       'BackgroundColor',bgColor,...
       'FontSize',fontSize,...
       'FontWeight','bold',...
       'HorizontalAlignment','left',...
       'Position', [round(0.3*width) height-30-(fontSize*1.5) ...
                    round(0.65*width) fontSize*4]);
                
                

uicontrol(f,'Style', 'text',...
       'String', 'Manifold Embedding Neuroimage Analysis (MENA)',...
       'BackgroundColor',bgColor,...
       'FontSize',fontSize,...
       'HorizontalAlignment','left',...
       'Position', [round(0.3*width) height-50-(fontSize*1.5) ...
                    round(0.65*width) fontSize*2]);

uicontrol(f,'Style', 'text',...
       'String', 'Author: Felipe Orihuela-Espina',...
       'BackgroundColor',bgColor,...
       'FontSize',fontSize,...
       'HorizontalAlignment','left',...
       'Position', [round(0.3*width) height-80-(fontSize*1.5) ...
                    round(0.65*width) fontSize*2]);

uicontrol(f,'Style', 'text',...
       'String', '(c) 2008-19 Felipe Orihuela-Espina. Imperial College',...
       'BackgroundColor',bgColor,...
       'FontSize',fontSize,...
       'HorizontalAlignment','left',...
       'Position', [round(0.3*width) height-110-(fontSize*1.5) ...
                    round(0.65*width) fontSize*2]);


                
A=imread('./GUI/icons/ICNNA_jack.jpg','jpeg');
image(A);
set(gca,'Tag','logoAxes',...
       'Color','w',...
       'FontSize',fontSize,...
       'Units','normalize',...
       'Position', [0.02 0.73 0.18 0.25]);
       %'Position', [0.02 0.58 0.25 0.35]);
axis off

ackString={'Current version: 1.1.4',...
    '',...
    '=================================',...
    '== Contributions ',...
    '=================================',...
    ['Research: Dr. Felipe Orihuela-Espina, Dr. Daniel Leff, '...
    'Dr. Dave James, Prof. Sir Ara Darzi and Prof. Guang-Zhong Yang'],...
    '', ...
    ['Beta testing: Dr. Felipe Orihuela-Espina, Mr. Marco Caproni, ' ...
    'Dr. Dave James, Dr. Kunal Shetty and Dr. Samuel A. Montero-Hernández, ' ...
    'Dr. Harsimrat Singh, Mrs. Michele Rojas Cisneros.'],...
    '', ...
    '=================================',...
    '== External sources code and algorithms',...
    '=================================',...
    ['In some cases, ICNNA uses code not only from basic MATLAB, ' ...
    'software package ' ...
    'but also from other sources but ditributed under ' ...
    'licences. These are in some cases ' ...
    'copyright protected, and their rights belong to ' ...
    'their authors.'],...
    ['While every effort is made to recognise other people copyright, ' ...
    'if you think we''are missing someone/something please let us ' ...
    'know.'], ...
    '', ...
    ['fNIRS conversion, filtering and detrend algorithms are '...
    'inspired in fOSA (UCL - University College London).'], ...
    '', ...
    'Function cmdscale => (c) MATLAB Statistics Toolbox',...
    'Function tpvalue.m => (c) MATLAB (Isolated from corrcoef.m)',...
    'Function cca => (c) SOM Toolbox',...
    'Function kldiv => (c) David Fass',...
    'Functions kmeans, dist2 => (c) netlab. Ian T Nabney (1996-2001)',...
    'Isomap algorithm => (c) Tenenbaum',...
    ''};
    
uicontrol(f,'Style', 'edit',...
       'Min',0,...
       'Max',2,...
       'String', ackString,...
       'BackgroundColor',bgColor,...
       'FontSize',fontSize,...
       'HorizontalAlignment','left',...
       'Units','normalize',...
       'Position', [0.02 0.02 0.96 0.65]);
%        'Position', [round(0.02*width) height-290-(fontSize*1.5) ...
%                     round(0.96*width) 10*(fontSize*1.5)]);



%% Make GUI visible
set(f,'Name','About ICNNA');
movegui(f,'center'); %Move the window to the center of the screen
set(f,'Visible','on');


end