function guiICNNA
%ICNNA main menu
%
% guiICNNA - Displays ICNNA's main menu
%
%
% Copyright 2008-2023
% @author Felipe Orihuela-Espina
%
% See also guiAnalysis, guiExperiment, guiExperimentSpace
%


%% Log
%
% File created: 6-Oct-2008
% File last modified (before creation of this log): 25-Apr-2018
%
% 25-Apr-2018: FOE. Renamed from icna to icnna. Call to about box
%   updated.
%
% 13-May-2023: FOE
%   + Got rid of old labels @date and @modified.
%   + Renamed from icnna to guiICNNA to avoid conflict with new
%   objects package +icnna
%





%% Initialize the figure
%...and hide the GUI as it is being constructed
width=300;
height=320;
f=figure('Visible','off','Position',[200,400,width,height]);
set(f,'NumberTitle','off');
set(f,'MenuBar','none'); %Hide MATLAB figure menu
%set(f,'CloseRequestFcn',{@OnClose_Callback});
movegui(f,'northwest');

fontSize=16;
bgColor=get(f,'Color');
uicontrol(f,'Style', 'text',...
       'String', 'ICNNA',...
       'BackgroundColor',bgColor,...
       'FontSize',fontSize,...
       'FontAngle','italic',...
       'FontSize',32,...
       'FontWeight','bold',...
       'HorizontalAlignment','center',...
       'Units','normalize',...
       'Position', [0.1 0.72 0.8 0.25]);

   
   
   
buttonPanel = uipanel(f,...
        'BorderType','none',...
		'FontSize',fontSize-4,...
        'BackgroundColor',get(f,'Color'),...
        'Position',[0.02 0.02 0.96 0.7]);

uicontrol(buttonPanel,'Style', 'pushbutton',...
       'String', 'Data uploading',...
       'Tag','experimentButton',...
       'BackgroundColor',bgColor,...
       'FontSize',fontSize,...
       'HorizontalAlignment','center',...
       'Units','normalize',...
       'Position', [0.05 0.82 0.9 0.19],...
       'Callback',{@OnExperiment_Callback});
uicontrol(buttonPanel,'Style', 'pushbutton',...
       'String', 'MENA Analysis',...
       'Tag','analysisButton',...
       'BackgroundColor',bgColor,...
       'FontSize',fontSize,...
       'HorizontalAlignment','center',...
       'Units','normalize',...
       'Position', [0.05 0.62 0.9 0.19],...
       'Callback',{@OnAnalysis_Callback});
uicontrol(buttonPanel,'Style', 'pushbutton',...
       'String', 'Database generation',...
       'Tag','expSpButton',...
       'BackgroundColor',bgColor,...
       'FontSize',fontSize,...
       'HorizontalAlignment','center',...
       'Units','normalize',...
       'Position', [0.05 0.42 0.9 0.19],...
       'Callback',{@OnDatabaseGeneration_Callback});
uicontrol(buttonPanel,'Style', 'pushbutton',...
       'String', 'About ICNNA/MENA',...
       'Tag','aboutButton',...
       'BackgroundColor',bgColor,...
       'FontSize',fontSize,...
       'HorizontalAlignment','center',...
       'Units','normalize',...
       'Position', [0.05 0.22 0.9 0.19],...
       'Callback',{@OnAbout_Callback});
uicontrol(buttonPanel,'Style', 'pushbutton',...
       'String', 'Exit',...
       'Tag','exitButton',...
       'BackgroundColor',bgColor,...
       'FontSize',fontSize,...
       'HorizontalAlignment','center',...
       'Units','normalize',...
       'Position', [0.05 0.02 0.9 0.19],...
       'Callback',{@OnExit_Callback});

%% On Opening
handles = guihandles(f); %NOTE that only include those whose 'Tag' are not empty
guidata(f,handles);
%myRedraw(f);

%% Make GUI visible
set(f,'Name','ICNNA - MENA Analysis');
set(f,'Visible','on');
%waitfor(f);




%% OnAbout callback
%Opens the "About ICNNA" information window
function OnAbout_Callback(hObject,eventData)
% hObject - Handle of the object, e.g., the GUI component,
%   for which the callback was triggered.  See GCBO
% eventdata - Reserved for later use.
aboutICNNA;
end

%% OnAnalysis callback
%Opens the guiAnalysis for data analysis
function OnAnalysis_Callback(hObject,eventData)
% hObject - Handle of the object, e.g., the GUI component,
%   for which the callback was triggered.  See GCBO
% eventdata - Reserved for later use.
guiAnalysis;
end


%% OnDatabaseGeneration callback
%Opens the guiExperimentSpace for database generation
function OnDatabaseGeneration_Callback(hObject,eventData)
% hObject - Handle of the object, e.g., the GUI component,
%   for which the callback was triggered.  See GCBO
% eventdata - Reserved for later use.
guiExperimentSpace(experimentSpace);
end


%% OnExit callback
%Exit ICNA
function OnExit_Callback(hObject,eventData)
% hObject - Handle of the object, e.g., the GUI component,
%   for which the callback was triggered.  See GCBO
% eventdata - Reserved for later use.
close(f);
end

%% OnExperiment callback
%Opens the guiExperiment for data loading and manipulation
function OnExperiment_Callback(hObject,eventData)
% hObject - Handle of the object, e.g., the GUI component,
%   for which the callback was triggered.  See GCBO
% eventdata - Reserved for later use.
guiExperiment;
end


end