classdef rawData < icnna.data.core.identifiableObject
% icnna.data.core.rawData Data in propietary format
% 
% This class supersedes class |rawData|.
% 
%   This is an abstract class.
%
%A icnna.data.core.rawData represents data available in propietary
%formats.
% 
% icnna.data.core.rawData may have been generated by any kind of sensing
%device (neuroimaging device, tracker, physiological meter or other).
%
% Due to the variability of the sources, the external formats may be
%very different. This class is an extremely simple abstract class to 
%accomodate all the possible raw data under a common roof.
%
%
%% Differences to original class |rawData|
% In contrast to original class @rawData;
% 
%   * This class does NOT store the data in memory. Instead,
%   it only "points to" the files and reads the files on demand
%   when method |import| is called. This:
%       + Increases the time to access the raw data in general as
%       now, |import| needs to be called every time, however,
%       + This reduces the memory needed to keep track of the
%       rawData, and it is now up to the user to decide whether
%       he wants to keep a structured version of the raw data in
%       memory. 
%       + Since experience tells that importing the data is a one-off
%       method, where as moving the other value-class objects around
%       is costly, a collateral effect is that copying the
%       dataSource objects will be faster, compensating for the
%       higher cost of the new |import|.       
%   * This class does NOT assume that the data is un-reconstructed
%   (and hence, no |cenvert|) nor un-processed.
%   * The abstract method |convert| originally intended to perform
%   reconstruction, is no longer available. Instead, alternative
%   polymorphic methods (icnna.op.*) are available for reconstruction
%   when applicable.
%   * rawData no longer is assumed to start on a file e.g. as |import|
%   abstract method did. Instead, folders containing data will also
%   be readily acceptable as rawData. Right now, this is more like a
%   NIRx session folder where there are several files, rather than a
%   BIDS structure. BIDS structure will have its own full support.
%   * Abstract method |import| no longer reutrn a rawData (it returns
%   a structuredData data instead) nor it requires a parameter for the
%   location of the data and instead now relies on new property .path.
%
%       + BEFORE: myRawData = myRawData.import(filename,...);
%       + NOW EITHER: myRawData.path = filepath;
%                     raw_structured_content = import(myRawData,...);
%
%       Note that the raw_structured_data produced by import
%       is NOT what used to be the output of method |convert|
%       as import does NOT performs reconstruction of any kind.
%   * Multi modal data (if considered a single conceptual data stream)
%   is permitted, and the outcome will be aggregated into a single
%   structuredData when calling |import|. Separated modality support
%   may also be provided for each substream or independent
%   rawData implementing classes.
%   * Specific file conversion methods may be covered
%   by different
% 
% Hence, the implementing classes must still know how to read the external
%format (method import) but no longer needs to know how to convert
%(reconstruct) the information to a class ready for processing and
%analysis such as |structuredData| or |iccna.data.snirf.snirf|.
%
%% Remarks
%
%   This is an Abstract class.
%
%   Watch out! The |path| may be modified AFTER calling method |import|
% but no consistency check is made. In other words, although it is expected
% that the |path| corresponds to the imported data but there is no
% guarantee. Same with |dataFiles| and |date|.
%
%
%% Known subclasses
%
% icnna.data.misc.rawData_NIRx - fNIRS measurement data in NIRx propietary
%       format.
%
%
%% Properties
%
%   -- Private properties
%   .classVersion - Char array. (Read only. Constant)
%       The class version of the object
%       This is separate from the superclass' own |classVersion|.
%
%   -- Inherited properties
%   .id - uint32. Default is 1.
%       A numerical identifier.
%   .name - (Since v1.4.0) Char array. By default is 'rawData0001'.
%       A name for the timeline. 
%
%   -- Public properties
%   .description - Char array. Default is 'Raw data'.
%       A short description.
%   .date - Datetime. Default value is datetime('now').
%       A datetime associated with the acquisition of the
%       icnna.data.core.rawData. 
%       The class ensure that the folder separator automatically adjusts
%       depending on the operating system.
%   .path - Char array. Default value is ['.' filesep]
%       The file or folder from where the original data was read.
%       It should not contain the filename (see property |dataFiles|).
%       * Available since class version 1.0.
%   .dataFiles - struct[]
%       The files containing the raw data. Each struct refers to a single
%       file, and has the following fields.
%       .filename - char[]. Default is empty.
%           The name of the file contaning the data.
%           The filenames are relative to the |path| and contain the
%           extension.
%           The class ensure that if any filename further contains some
%           additional path, the folder separator is automatically adjusted
%           depending on the operating system.
%
%   +====================================================+
%   | ICNNA does NOT act as a DBMS and does not put any  |
%   | kind of lock of the original data files. Since the |
%   | files (end even the paths) may be manipulated      |
%   | externally, there is no guarantee that the |path|, |
%   | nor the |dataFiles| remain consistent with the     |
%   | values store in an instance object of this class.  |
%   +====================================================+
%
%       .description - char[]. Default is empty.
%           A short description of the content of the file.
%  
%% Methods
%
% Type methods('rawData') for a list of methods
%
%
% Copyright 2025
% @author: Felipe Orihuela-Espina
%
% See also rawData
%




%% Log of old class |rawData| before the creation of this class.
%
% File created: 12-May-2008
% File last modified (before creation of this log): 4-Apr-2018
%
% 4-Apr-2018 (FOE): Added known subclasses.
%
%
% 13-May-2023: FOE
%   + Got rid of old labels @date and @modified.
%   + Added property classVersion. Set to '1.0' by default.
%   + Added get/set methods support for struct like access to attributes.
%   + For those attributes above also started to simplify the set
%   code replacing it with validation rules on the declaration.
%   + Improved some comments.
%

%% Log
%
%   + Class available since ICNNA v1.2.3
%
% 2-Feb-2025: FOE
%   + File and class created. Part of the code is inherited from
%   old class |rawData| (dating back to 2008 - See above).
%   + Property |date| is now of type datetime.
%   + Property |path| added.
%   + Property |dataFiles| added.
%
%
% -- ICNNA v1.4.0
%
% 13-Dec-2025: FOE
%   + The class is now identifiable.
%   + Class version - Updated to 1.1
%	+ Improved some comments
%   + Class constructor accepting |id| as parameter has been eliminated.
%   + Added method classVersion
%   + |path| and |dataFiles| now automatically updates the file separator.
%
% 20-Dec-2025: FOE
%   + |dataFiles| no longer store the content of the
%   file, but a brief description. Also, internal representation
%   of this property has been changed from a dictionary to
%   a struct array (each struct being a file pointer).
%   + No need to further update the class version, as this
%   has already been updated for ICNNA v1.4.0.
%	+ Improved some comments
%

    properties (Constant, Access=private)
        classVersion = '1.1'; %Read-only. Object's class version.
    end



    properties %(SetAccess=private, GetAccess=private)
        description(1,:) char = 'Raw data'; %A short description of the data.
        date=datetime('now'); %Acquisition date as character vector.
        path(1,:) char = ['.' filesep]; %The folder or filename from where the original data was read.
        dataFiles struct = struct( ...
            'filename', {}, ...
            'description', {} ); %The list of files containing the raw data.
    end
 
    % =====================================================================
    % Constructor
    % =====================================================================
    methods    
        function obj=rawData(varargin)
            %Constructor for class @icnna.data.core.rawData
            %
            % obj=icnna.data.core.rawData() creates a default empty rawData.
            % obj=icnna.data.core.rawData(obj2) acts as a copy constructor of rawData
            %
            % 
            % Copyright 2024-25
            % @author: Felipe Orihuela-Espina
            %

            obj@icnna.data.core.identifiableObject();
            tmp = split(class(obj),'.');
            obj.name = [tmp{end} num2str(obj.id,'%04d')];
            if (nargin==0)
                %Keep default values
            elseif isa(varargin{1},'icnna.data.core.rawData')
                obj=varargin{1};
                return;
            else
                error(['icnna.data.core.rawData:rawData:InvalidNumberOfParameters' ...
                            'Unexpected number of parameters.']);
            end
            %assertInvariants(obj);

        end
   
    end



    methods (Abstract=true)
        sd=import(obj,varargin); %Reads the files storing the raw data
                                 %and returns a structured version of the
                                 %raw data.
    end



    % =====================================================================
    % Getters & setters
    % =====================================================================
    methods

        %Retrieves the |description| of the object
        function val = get.description(obj)
            % Getter for |description|:
            %   Returns the |description| property.
            %
            % A short description of the object.
            %
            % Usage:
            %   res = obj.description;  % Retrieves the object's description.
            %
            %% Output
            % res - char[]
            %   The description of the object.
            %
            val = obj.description;
        end
        %Sets the |description| of the object
        function obj = set.description(obj,val)
            % Setter for |description|:
            %   Sets the |description| property.
            %
            % The description of the object.
            %
            % Usage:
            %   obj.description = 'Foo';  % Set the |description| to 'Foo'.
            %
            %% Input parameters
            %
            % val - char[]
            %   The new |description|.
            %
            %% Output
            %
            % obj - @icnna.data.core.rawData
            %   The updated object
            %
            obj.description = val;
        end


         %Retrievs the object |date|
      function res = get.date(obj)
            % Getter for |date|:
            %   Returns the |date| property.
            %
            % Usage:
            %   res = obj.date;  % Retrieves the date.
            %
            %% Output
            % res - datetime
            %   A datetime associated with the acquisition of the
            %   @icnna.data.core.rawData.
            %
         res = obj.date;
      end
         %Sets the object |date|
      function obj = set.date(obj,val)
            % Setter for |date|:
            %   Sets the |date| property.
            %
            % Usage:
            %   obj.date = datetime('now');  % Set the |date| to the present time.
            %
            %% Input parameters
            %
            % val - datetime
            %   A datetime associated with the acquisition of the
            %   @icnna.data.core.rawData.
            %
            %% Output
            %
            % obj - @icnna.data.core.rawData
            %   The updated object
            %
         obj.date = val;
      end



         %Retrieves the object |path|
      function res = get.path(obj)
            % Getter for |path|:
            %   Returns the |path| property.
            %
            % Usage:
            %   res = obj.path;  % Retrieves the path to the raw data files.
            %
            %% Output
            % res - char[]
            %  The file or folder from where the original data was read.
            %

         %Update the folder separators
         idx = find(obj.path == '\' | obj.path == '/');
         obj.path(idx) = filesep;
         res = obj.path;
      end
         %Sets the object |path|
      function obj = set.path(obj,val)
            % Setter for |path|:
            %   Sets the |path| property.
            %
            % Usage:
            %   obj.path = ['.' filesep];  % Set the |path| to './'.
            %   obj.path = ['.'];  % Set the |path| also to './'.
            %
            %% Input parameters
            %
            % val - char[]
            %  The file or folder from where the original data is to
            %  be read. It should not contain the file names (see
            %  property |dataFiles| instead).
            %   If the last directory separator is not included
            %  it will be automatically added.
            %
            %% Output
            %
            % obj - @icnna.data.core.rawData
            %   The updated object
            %
         %Update the folder separators
         idx = find(val == '\' | val == '/');
         val(idx) = filesep;
         if (val(end) ~= filesep)
             val = [val filesep];
         end
         obj.path = val;
      end

         %Retrieves the object's |dataFiles|
      function res = get.dataFiles(obj)
            % Getter for |dataFiles|:
            %   Returns the |dataFiles| property.
            %
            % If files are not in the current folder,
            %
            % Usage:
            %   res = obj.dataFiles;  % Retrieves the list of file names
            %                         %containing the raw data.
            %
            %% Output
            % res - dictionary
            %   The list of files read (keys) and their contents (values).
            %

             %Update the folder separators
             nFiles = numel(obj.dataFiles);
             for iFile = 1:nFiles
                 nameStr    = obj.dataFiles(iFile).filename; % Extract the string from the struct array
                 newNameStr = strrep(nameStr, '\', filesep); %Update the folder separators
                 newNameStr = strrep(nameStr, '/', filesep);
                 obj.dataFiles(iFile).filename = newNameStr;
             end

         res = obj.dataFiles;
      end
         %Sets the object's |dataFiles|
      function obj = set.dataFiles(obj,val)            % Setter for |path|:
            %   Sets the |path| property.
            %
            % Usage:
            %   obj.path = ['.' filesep];  % Set the |path| to './'.
            %
            %% Input parameters
            %
            % val - char[]
            %  The file or folder from where the original data was read.
            %  It should not contain the filename (see property |dataFiles|).
            %
            %% Output
            %
            % obj - @icnna.data.core.rawData
            %   The updated object
            %


            % Validation
            assert(isstruct(val), ...
                ['icnna.data.misc.rawData:set_dataFiles:InvalidParameterValue' ...
                 'dataFiles must be a struct array']);
            assert(all(isfield(val, {'filename','description'})), ...
                   ['icnna.data.misc.rawData:set_dataFiles:InvalidParameterValue' ...
                    'Struct must have filename and description fields.']);

            % Ensure char arrays
            for k = 1:numel(val)
                assert(ischar(val(k).filename), ...
                    ['icnna.data.misc.rawData:set_dataFiles:InvalidParameterValue' ...
                     'Field .filename must be char[].']);
                assert(ischar(val(k).description), ...
                    ['icnna.data.misc.rawData:set_dataFiles:InvalidParameterValue' ...
                      'Field .description must be char[].']);

                 %Update the folder separators
                 nFiles = numel(val);
                 for iFile = 1:nFiles
                     nameStr    = val(iFile).filename; % Extract the string from the struct array
                     newNameStr = strrep(nameStr, '\', filesep); %Update the folder separators
                     newNameStr = strrep(nameStr, '/', filesep);
                     val(iFile).filename = newNameStr;
                 end
                
            end

            %Finally, store the value.
            obj.dataFiles = newVal;

      end

    end

end
