function v = version()
% Returns ICNNA''s current running version.
% 
%   v = icnna.util.version()
% 
% WARNING:
%   Do NOT manually edit this file! Manual changes may result in
%   inconsistencies in ICNNA version reporting and may break reproducibility.
% 
%% Remarks
% 
% This file was automatically generated by icnna_releaseVersion.m
% It provides the current running version of ICNNA.
% 
% This is a read-only function. To update the version, use:
%   icnna_releaseVersion(''x.y.z'');
% 
%% Example of usage:
% 
%   v = icnna.util.version(); % returns the version string
% 
%% Input parameters
% 
% N/A
% 
%% Output
% 
% v - string
%   ICNNA's current running version.
% 
% 
% Copyright 2026
% @author Felipe Orihuela-Espina
% 
% See also icnna_releaseVersion
% 

%% Log
%
%
% Function created: 7-May-2026
%
% -- ICNNA v1.4.1 (after beta)
% 
% 7-May-2026: FOE. 
%   + Function created
%
%

% Automatically generated by auxiliary function create_icnna_version_file
% within icnna_releaseVersion.m
v = '1.4.1';

end