function f=aboutHRTool()
%About box for the Heart Rate tool
%
%
% Copyright 2009
% @date: 19-Jan-2009
% @author Felipe Orihuela-Espina
%

%% Initialize the figure
%...and hide the GUI as it is being constructed
width=500;
height=320;
f=figure('Visible','off','Position',[300,300,width,height]);
set(f,'NumberTitle','off');
set(f,'MenuBar','none'); %Hide MATLAB figure menu

%% Add components
fontSize=13;
bgColor=get(f,'Color');
htextCopyright=uicontrol('Style', 'text',...
       'String', ['HR Tool, A tool for heart rate analysis'],...
       'BackgroundColor',bgColor,...
       'FontSize',fontSize,...
       'HorizontalAlignment','left',...
       'Position', [round(0.05*width) height-20-(fontSize*1.5) ...
                    round(0.9*width) fontSize*1.5]);

htextCopyright=uicontrol('Style', 'text',...
       'String', 'HRTool is part of ICAF',...
       'BackgroundColor',bgColor,...
       'FontSize',fontSize,...
       'HorizontalAlignment','left',...
       'Position', [round(0.05*width) height-50-(fontSize*1.5) ...
                    round(0.9*width) fontSize*1.5]);

htextAuthor=uicontrol(f,'Style', 'text',...
       'String', 'Author: Felipe Orihuela-Espina',...
       'BackgroundColor',bgColor,...
       'FontSize',fontSize,...
       'HorizontalAlignment','left',...
       'Position', [round(0.05*width) height-80-(fontSize*1.5) ...
                    round(0.9*width) fontSize*1.5]);

htextCopyright=uicontrol('Style', 'text',...
       'String', ['(c) 2009 Felipe Orihuela-Espina. '...
                    'Imperial College London'],...
       'BackgroundColor',bgColor,...
       'FontSize',fontSize,...
       'HorizontalAlignment','left',...
       'Position', [round(0.05*width) height-110-(fontSize*1.5) ...
                    round(0.9*width) fontSize*1.5]);

                

% A=imread('./GUI/icons/hrtool.jpg','jpeg');
% image(A);
% set(gca,'Tag','logoAxes',...
%        'Color','w',...
%        'FontSize',fontSize,...
%        'Units','normalize',...
%        'Position', [0.37 0.15 0.26 0.35]);
% axis off

%% Make GUI visible
set(f,'Name','About HRTool');
movegui(f,'center'); %Move the window to the center of the screen
set(f,'Visible','on');

end